#!/bin/sh


echo ""
echo "##########################################################################"
echo "#                  NADCO-2D Soccer Simulation 2D Team                    #"
echo "#                                                                        #"
echo "#     Department Of Artificial Intelligence & Multi Agent Simulation     #"
echo "#                NADCO Educational Robotics Corporation                  #"
echo "#                            Tehran - Iran                               #"
echo "#                                                                        #"
echo "#                     Mohammad Ali Sadeghi Marasht                       #"
echo "#                          Head of Department                            #"
echo "#                                                                        #"
echo "#                        http://www.nad-co.com                           #"
echo "##########################################################################"
echo ""


HOST=$1

teamname="NADco-2D"

player="./sample_player"

config="player.conf"
config_dir="./formations-dt"
coach_config="coach.conf"

opt="--player-config ${config} --config_dir ${config_dir}"
opt="${opt} -h ${HOST} -t ${teamname}"

coachopt="--coach-config ${coach_config}"
coachopt="${coachopt} -h ${HOST} -t ${teamname}"

$player ${opt} -g &
sleep 1

$player ${opt} &
sleep 0.5
$player ${opt} &
sleep 0.5
$player ${opt} &
sleep 0.5
$player ${opt} &
sleep 0.5
$player ${opt} &
sleep 0.5
$player ${opt} &
sleep 0.5
$player ${opt} &
sleep 0.5
$player ${opt} &
sleep 0.5
$player ${opt} &
sleep 0.5
$player ${opt} &
sleep 1
$player --coach ${coachopt} &

wait
